Projects_2023/C#.NET Apps/YouTubeProjects/YTP.Main/Areas/CarRentalSystem/Models/RentalViewModel.cs
using System;

namespace YTP.Main.Areas.CarRentalSystem {
    public class RentalViewModel {
        public int id { get; set; }
        public string carid { get; set; }
        public int? custid { get; set; }
        public int? fee { get; set; }
        public DateTime? sdate { get; set; }
        public DateTime? edate { get; set; }
        public string available { get; set; }
    }
}

Projects_2023/C#.NET Apps/YouTubeProjects/YTP.Main/Areas/CarRentalSystem/Controllers/RentalController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using YTP.Main.DataAccess;

namespace YTP.Main.Areas.CarRentalSystem.Controllers {
    public class RentalController : Controller {

        readonly YTP_DBContext _db = new YTP_DBContext();

        // GET: Rental
        public ActionResult Index() {

            var result = (from r in _db.rentals
                          join c in _db.carregs
                          on r.carid equals c.carno
                          select new RentalViewModel {
                              id = r.id,
                              carid = r.carid,
                              custid = r.custid,
                              fee = r.fee ?? 100,
                              sdate = r.sdate,
                              edate = r.edate,
                              available = c.available
                          }).ToList();

            if(result.Count == 0)
                ViewBag.DisplayRentals = false; // There is an error here to be solved.
            

            return View(result);
        }

        [HttpGet]
        public ActionResult GetCar() {

            return Json(_db.carregs.ToList(), JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult Getid(int id) {

            var customer = (from c in _db.customers where c.id == id select c.custname).ToList();
            return Json(customer, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult CheckAvailability(string carno) {

            var availability = (from c in _db.carregs where c.carno == carno select c.available).FirstOrDefault();
            return Json(availability, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public ActionResult Save(rental rental) {
            if (ModelState.IsValid) {
                _db.rentals.Add(rental);

                var car = _db.carregs.FirstOrDefault(c => c.carno == rental.carid);
                if (car == null) return HttpNotFound("Car No NOT FOUND");

                car.available = "no";
                _db.Entry(car).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(rental);
        }
    }
}

Projects_2023/C#.NET Apps/YouTubeProjects/YTP.Main/Areas/CarRentalSystem/Views/Rental/Index.cshtml
<div class="row mt-3">
    <div></div>
    <div class="col-sm-4">
        @using (Html.BeginForm("Save", "Rental", FormMethod.Post, new { id = "popupForm" })) {

            <div><h1>Car Rental</h1></div>

            <div class="form-group">
                <div class="form-label">Car No</div>
                <select class="form-control" id="carid" name="carid" required>
                    <option>Please Select</option>
                </select>
            </div>

            <div class="form-group">
                <div class="form-label">Customer ID</div>
                <input class="form-control" type="text" id="custid" name="custid" placeholder="Customer ID" required />
            </div>

            <div class="form-group">
                <div class="form-label">Customer Name</div>
                <input class="form-control" type="text" id="custname" name="custname" placeholder="Customer Name" required />
            </div>

            <div class="form-group">
                <div class="form-label">Rental Fee</div>
                <input class="form-control" type="text" id="rentalfee" name="rentalfee" placeholder="Rental Fee" required />
            </div>

            <div class="form-group">
                <div class="form-label">Start Date</div>
                <input class="form-control" type="date" id="sdate" name="sdate" placeholder="Start Date" required />
            </div>

            <div class="form-group">
                <div class="form-label">End Date</div>
                <input class="form-control" type="date" id="edate" name="edate" placeholder="End Date" required />
            </div>

            <div class="form-group">
                <input class="btn btn-success" value="Save Record" type="submit" />
            </div>

        }

    </div>

    <div class="col-sm-8" style="background-color:whitesmoke;">
        @if (ViewBag.DisplayRentals) {
            string messageToDisplay = "There's no data to display.";
            Html.RenderPartial("_NoData", messageToDisplay);
        } else {

            Html.RenderPartial("_ListAllRentals");
        }
    </div>

</div>

@section scripts {
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>


    <script>

        $(document).ready(function () {
            GetCar();
            GetCustomer();
            Load();
        });

        function Load() {
            $("#custid, #custname, #rentalfee, #sdate, #edate").attr("disabled", "disabled").val("");
        }


        function GetCar() {
            $.ajax({
                type: 'GET',
                url: '/Rental/GetCar',
                dataType: 'JSON',
                success: function (response) {

                    for (var i = 0; i < response.length; i++) {

                        $("#carid").append($("<option/>", { text: response[i].carno }));

                    }
                }
            });
        }

        $("#carid").change(function () {
            Load();
            checkCarAvailability();
        });

        function checkCarAvailability() {
            $.ajax({
                type: 'POST',
                url: '/Rental/CheckAvailability?carno=' + $("#carid").val(),
                dataType: 'JSON',
                success: function (response) {


                    if (response == "yes") {
                        $("#custid, #custname, #rentalfee, #sdate, #edate").removeAttr("disabled");

                    } else {
                        Load();
                    }

                }
            })
        }

        function GetCustomer() {
            $("#custid").keyup(function (e) {

                $.ajax({
                    type: 'POST',
                    url: '/Rental/Getid?id=' + $("#custid").val(),
                    dataType: 'JSON',
                    success: function (response) {

                        if (response == "" || response == null) {
                            $("#custname").val("Customer ID NOT FOUND!");
                        }
                        else
                            $("#custname").val(response);


                    }
                })

            })
        }


    </script>
}

Projects_2023/C#.NET Apps/YouTubeProjects/YTP.Main/Areas/CarRentalSystem/Views/Rental/_ListAllRentals.cshtml
@using YTP.Main.Areas.CarRentalSystem

@model IEnumerable<RentalViewModel>

<table class="table small">
    <thead class="table-dark">
        <tr>
            <th>Car No</th>
            <th>Customer ID</th>
            <th>Rental Fee</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Availability</th>
        </tr>
    </thead>
    @foreach (var item in Model) {
        <tr>
            <td>@item.carid</td>
            <td>@item.custid</td>
            <td>@item.fee</td>
            <td>@item.sdate</td>
            <td>@item.edate</td>
            <td>@item.available</td>
        </tr>
    }
</table>

Projects_2023/C#.NET Apps/YouTubeProjects/YTP.Main/Areas/CarRentalSystem/Views/Rental/_NoData.cshtml
@model string

<div class="alert alert-warning align-content-center">
    @Model
</div>